version: '3.8'

services:
  miniserver:
    build: ../Part5
    container_name: miniserver

  nginx_proxy:
    image: nginx:stable
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./start.sh:/start.sh
    ports:
      - 80:8080
